api_ai_webhook.settings:
  type: config_object
  label: 'Api.AI Webhook Settings'
  mapping:
    auth:
      type: mapping
      label: 'Authentication settings for Api.AI Webhook'
      mapping:
        type:
          type: string
          label: 'Auth type. It can be none, basic or header'
        values:
          type: sequence
          label: 'Auth type setting values'
          sequence:
            type: string
            label: 'Value'

chatbot_api_entities_push_handler_settings.api_ai_webhook:
  type: chatbot_api_entities_push_handler
  mapping:
    remote_id:
      type: string
      label: 'Remote ID'
    remote_name:
      type: string
      label: 'Remote name'
